CC=gcc
CFLAGS=-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -ggdb -Wall -Wextra 
TARGETS=glibtest.c

all: glibtest

glibtest: $(TARGETS)
	$(CC) $(CFLAGS) $^ -lglib-2.0 -o $@


.PHONY: clean
clean:
	@echo "Cleaning..."
	-rm -f glibtest
	@echo "Finished cleaning."
